# see https://github.com/marketplace/stale

daysUntilStale: 60
daysUntilClose: 14
exemptLabels:
  - pinned
  - security
staleLabel: won't fix
markComment: >
  The issue has been automatically marked as stale since it has not had recent activity;
  will be closed if no further activity occurs. TY for the contribution.
closeComment: false
exemptProjects: true
exemptMilestones: true
exemptAssignees: true
